export const ADMIN_ROLE_CODES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  COMPLIANCE_OFFICER: 'COMPLIANCE_OFFICER',
  PAYMENT_OFFICER: 'PAYMENT_OFFICER',
  PAYMENT_MANAGER: 'PAYMENT_MANAGER',
  ACCOUNT_MANAGER: 'ACCOUNT_MANAGER',
  CUSTOMER_SUPPORT: 'CUSTOMER_SUPPORT',
  TRANSACTION_AUDITOR: 'TRANSACTION_AUDITOR',
  LEDGER_OFFICER: 'LEDGER_OFFICER',
  RISK_FRAUD_OFFICER: 'RISK_FRAUD_OFFICER',
  OPERATIONS_MANAGER: 'OPERATIONS_MANAGER',
} as const;

export type AdminRoleCode =
  (typeof ADMIN_ROLE_CODES)[keyof typeof ADMIN_ROLE_CODES];

export const PERMISSION_CODES = {
  DASHBOARD_VIEW: 'DASHBOARD_VIEW',

  CUSTOMER_VIEW: 'CUSTOMER_VIEW',
  CUSTOMER_CREATE: 'CUSTOMER_CREATE',
  CUSTOMER_UPDATE: 'CUSTOMER_UPDATE',
  CUSTOMER_SUSPEND: 'CUSTOMER_SUSPEND',

  ACCOUNT_VIEW: 'ACCOUNT_VIEW',
  ACCOUNT_UPDATE: 'ACCOUNT_UPDATE',
  ACCOUNT_SUSPEND: 'ACCOUNT_SUSPEND',

  WALLET_VIEW: 'WALLET_VIEW',
  WALLET_CREATE: 'WALLET_CREATE',
  WALLET_UPDATE: 'WALLET_UPDATE',
  WALLET_FREEZE: 'WALLET_FREEZE',

  TRANSACTION_VIEW: 'TRANSACTION_VIEW',
  TRANSACTION_CREATE: 'TRANSACTION_CREATE',
  TRANSACTION_REVERSE: 'TRANSACTION_REVERSE',
  TRANSACTION_EXPORT: 'TRANSACTION_EXPORT',

  PAYMENT_VIEW: 'PAYMENT_VIEW',
  PAYMENT_CREATE: 'PAYMENT_CREATE',
  PAYMENT_APPROVE: 'PAYMENT_APPROVE',
  PAYMENT_REJECT: 'PAYMENT_REJECT',

  LEDGER_VIEW: 'LEDGER_VIEW',
  LEDGER_CREATE: 'LEDGER_CREATE',
  LEDGER_UPDATE: 'LEDGER_UPDATE',
  LEDGER_APPROVE: 'LEDGER_APPROVE',
  LEDGER_EXPORT: 'LEDGER_EXPORT',

  COMPLIANCE_VIEW: 'COMPLIANCE_VIEW',
  COMPLIANCE_REVIEW: 'COMPLIANCE_REVIEW',
  COMPLIANCE_APPROVE: 'COMPLIANCE_APPROVE',
  COMPLIANCE_RESTRICT: 'COMPLIANCE_RESTRICT',

  RISK_VIEW: 'RISK_VIEW',
  RISK_REVIEW: 'RISK_REVIEW',
  RISK_FLAG: 'RISK_FLAG',
  RISK_RELEASE: 'RISK_RELEASE',

  AUDIT_LOG_VIEW: 'AUDIT_LOG_VIEW',
  AUDIT_LOG_EXPORT: 'AUDIT_LOG_EXPORT',

  REPORT_VIEW: 'REPORT_VIEW',
  REPORT_EXPORT: 'REPORT_EXPORT',

  RECONCILIATION_VIEW: 'RECONCILIATION_VIEW',
  RECONCILIATION_RUN: 'RECONCILIATION_RUN',
  RECONCILIATION_APPROVE: 'RECONCILIATION_APPROVE',

  ADMIN_VIEW: 'ADMIN_VIEW',
  ADMIN_CREATE: 'ADMIN_CREATE',
  ADMIN_UPDATE: 'ADMIN_UPDATE',
  ADMIN_SUSPEND: 'ADMIN_SUSPEND',

  ROLE_VIEW: 'ROLE_VIEW',
  ROLE_CREATE: 'ROLE_CREATE',
  ROLE_UPDATE: 'ROLE_UPDATE',
  ROLE_ASSIGN: 'ROLE_ASSIGN',

  SYSTEM_SETTINGS_VIEW: 'SYSTEM_SETTINGS_VIEW',
  SYSTEM_SETTINGS_UPDATE: 'SYSTEM_SETTINGS_UPDATE',
} as const;

export type PermissionCode =
  (typeof PERMISSION_CODES)[keyof typeof PERMISSION_CODES];

export const ROLE_PERMISSIONS: Record<AdminRoleCode, PermissionCode[]> = {
  SUPER_ADMIN: Object.values(PERMISSION_CODES),

  COMPLIANCE_OFFICER: [
    PERMISSION_CODES.DASHBOARD_VIEW,
    PERMISSION_CODES.CUSTOMER_VIEW,
    PERMISSION_CODES.ACCOUNT_VIEW,
    PERMISSION_CODES.COMPLIANCE_VIEW,
    PERMISSION_CODES.COMPLIANCE_REVIEW,
    PERMISSION_CODES.COMPLIANCE_APPROVE,
    PERMISSION_CODES.COMPLIANCE_RESTRICT,
    PERMISSION_CODES.RISK_VIEW,
    PERMISSION_CODES.AUDIT_LOG_VIEW,
    PERMISSION_CODES.REPORT_VIEW,
  ],

  PAYMENT_OFFICER: [
    PERMISSION_CODES.DASHBOARD_VIEW,
    PERMISSION_CODES.CUSTOMER_VIEW,
    PERMISSION_CODES.ACCOUNT_VIEW,
    PERMISSION_CODES.WALLET_VIEW,
    PERMISSION_CODES.TRANSACTION_VIEW,
    PERMISSION_CODES.TRANSACTION_CREATE,
    PERMISSION_CODES.PAYMENT_VIEW,
    PERMISSION_CODES.PAYMENT_CREATE,
  ],

  PAYMENT_MANAGER: [
    PERMISSION_CODES.DASHBOARD_VIEW,
    PERMISSION_CODES.CUSTOMER_VIEW,
    PERMISSION_CODES.ACCOUNT_VIEW,
    PERMISSION_CODES.WALLET_VIEW,
    PERMISSION_CODES.TRANSACTION_VIEW,
    PERMISSION_CODES.PAYMENT_VIEW,
    PERMISSION_CODES.PAYMENT_APPROVE,
    PERMISSION_CODES.PAYMENT_REJECT,
    PERMISSION_CODES.REPORT_VIEW,
  ],

  ACCOUNT_MANAGER: [
    PERMISSION_CODES.DASHBOARD_VIEW,
    PERMISSION_CODES.CUSTOMER_VIEW,
    PERMISSION_CODES.CUSTOMER_UPDATE,
    PERMISSION_CODES.ACCOUNT_VIEW,
    PERMISSION_CODES.ACCOUNT_UPDATE,
    PERMISSION_CODES.WALLET_VIEW,
    PERMISSION_CODES.WALLET_UPDATE,
  ],

  CUSTOMER_SUPPORT: [
    PERMISSION_CODES.DASHBOARD_VIEW,
    PERMISSION_CODES.CUSTOMER_VIEW,
    PERMISSION_CODES.ACCOUNT_VIEW,
    PERMISSION_CODES.WALLET_VIEW,
    PERMISSION_CODES.TRANSACTION_VIEW,
  ],

  TRANSACTION_AUDITOR: [
    PERMISSION_CODES.DASHBOARD_VIEW,
    PERMISSION_CODES.TRANSACTION_VIEW,
    PERMISSION_CODES.TRANSACTION_EXPORT,
    PERMISSION_CODES.AUDIT_LOG_VIEW,
    PERMISSION_CODES.AUDIT_LOG_EXPORT,
    PERMISSION_CODES.REPORT_VIEW,
    PERMISSION_CODES.REPORT_EXPORT,
  ],

  LEDGER_OFFICER: [
    PERMISSION_CODES.DASHBOARD_VIEW,
    PERMISSION_CODES.WALLET_VIEW,
    PERMISSION_CODES.TRANSACTION_VIEW,
    PERMISSION_CODES.LEDGER_VIEW,
    PERMISSION_CODES.LEDGER_CREATE,
    PERMISSION_CODES.LEDGER_UPDATE,
    PERMISSION_CODES.LEDGER_EXPORT,
    PERMISSION_CODES.RECONCILIATION_VIEW,
    PERMISSION_CODES.RECONCILIATION_RUN,
  ],

  RISK_FRAUD_OFFICER: [
    PERMISSION_CODES.DASHBOARD_VIEW,
    PERMISSION_CODES.CUSTOMER_VIEW,
    PERMISSION_CODES.ACCOUNT_VIEW,
    PERMISSION_CODES.WALLET_VIEW,
    PERMISSION_CODES.TRANSACTION_VIEW,
    PERMISSION_CODES.RISK_VIEW,
    PERMISSION_CODES.RISK_REVIEW,
    PERMISSION_CODES.RISK_FLAG,
    PERMISSION_CODES.RISK_RELEASE,
    PERMISSION_CODES.COMPLIANCE_VIEW,
    PERMISSION_CODES.AUDIT_LOG_VIEW,
  ],

  OPERATIONS_MANAGER: [
    PERMISSION_CODES.DASHBOARD_VIEW,
    PERMISSION_CODES.CUSTOMER_VIEW,
    PERMISSION_CODES.ACCOUNT_VIEW,
    PERMISSION_CODES.WALLET_VIEW,
    PERMISSION_CODES.TRANSACTION_VIEW,
    PERMISSION_CODES.PAYMENT_VIEW,
    PERMISSION_CODES.LEDGER_VIEW,
    PERMISSION_CODES.RECONCILIATION_VIEW,
    PERMISSION_CODES.RECONCILIATION_RUN,
    PERMISSION_CODES.REPORT_VIEW,
    PERMISSION_CODES.REPORT_EXPORT,
    PERMISSION_CODES.AUDIT_LOG_VIEW,
  ],
};